### ISSUE TITLE
Controls option doesn't work with Events

### ISSUE THREAD

**Issue by StefanHyde** [u-wave/react-vimeo#280] opened 2024-07-30 15:22 UTC
Hi,

I have an issue with my streaming app (using React 17).

When the app is playing Vimeo events, most of the options from the SDK don't work.
For instance, when I set controls to false to display only my custom controls, the native controls still appear.

![Capture d’écran 2024-07-08 à 17 29 12](https://github.com/user-attachments/assets/e69242cd-cfec-40a3-951e-9c4ae327f559)

I tried on another project (React 18) with using the official lib from Vimeo : 
https://github.com/vimeo/player.js

Same issue ! 
<img width="777" alt="Capture d’écran 2024-07-30 à 16 50 41" src="https://github.com/user-attachments/assets/b06d493d-3e62-4db8-91c7-bd6b5ce1aa32">

Has anyone else encountered the same problem?

Thanks !

**Comment by goto-bus-stop** [comment] 2024-12-09 11:13
react-vimeo doesn't do anything special for events, and as I never used them, I'm not sure what the problems are or what the behaviour should be. I think it would be best if someone who actually uses live events can figure out the appropriate behaviours and implement them. I'll close this as a duplicate of https://github.com/u-wave/react-vimeo/issues/153

**Closed as not planned by goto-bus-stop** 2024-12-09 11:13 UTC
